name: Repository Events
on:
  push:
    branches:
      - main
      - "feature/*" # matches feature/featA, feature/featB, does not matches feature/featA/featB
      - "feature/**" # matches feature/featA, feature/featB, feature/featA/featB
      - "!feature/featA"
    # branches-ignore: 
      - feature/featA
    tags:
      - v1.* # match v1.1, v1.1.2
      - "!v1.1.1"
    paths:
      - "**.py"
      - "!app.js"
    # paths-ignore: # to ignore the path
    # - "**/node_modules/**"
  pull_request:
    types: [opened, assigned, reopened, synchronize]
    branches:
      - main
    paths: 
      - "**.py"  
  issues:
    types: [opened]

jobs:
  checkout-test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v4